### ISSUE TITLE
Absolute path not supported?

### ISSUE THREAD

**Issue by Graecos** [mittermichal/Anders.Gaming.LibTech3#5]
Hello,

I tried to put " " and ' ' around the absolute path to make it understandable but the function seems not to be supported.

Am I wrong in my typing or aren't absolute paths supported?

![image](https://user-images.githubusercontent.com/8597873/103439652-0aa26e80-4c3f-11eb-8c35-033d3b68a9b9.png)

**Comment by mittermichal** [comment]
hello
backslash `\` works for me on windows :)
so `C:\Users\...`
or for your case you can use relative path `demos\demos\05-10-ODC...`

**Comment by Graecos** [comment]
Yeah... I saw that after having written the ticket...
I just tested as well and it worked. Sorry for the inconvenience!
